### ISSUE TITLE
Merging Tasks

### ISSUE THREAD

**Issue by simon-tarr** [Azure/doAzureParallel#175] opened 2017-11-27 10:35 UTC
Is there a doAzureParallel 'recommended' way to merge (very) large lists after analysis?

I have a loop of ~500,000 iterations running across a 16-node pool. The Azure processing time within the foreach loop is fast but merging a list that long takes a very long time - much longer than the time taken to carry out the analysis.

I have set a number of arguments which should improve the time taken to return the completed list but they've made very little difference (if any) to the total processing time. These arguments are:

 .inorder=F - List order isn't important
.combine = function(...) rbindlist(list(...)) - Apparently rbindlist is faster than the default

I have copied my loop below. It's essentially trying to brute-force the start values for a non-linear model. It is running through all combinations of coefficients (in the object st1.1) until it finds a set of parameters which doesn't result in some sort of convergence error. Those iterations which fail should be removed (.errorhandling=c('remove')) leaving me with a list of potential start values out of the original 500,000.

```
 mod1.1<-foreach(i = 1:nrow(st1.1), .errorhandling=c('remove'), .inorder=FALSE, .combine = function(...) rbindlist(list(...)), .options.azure = opt, .packages = c("nls2")) %dopar% {
   nls(xx2~b0+b1*exp(b2*xx), data=xx.df, start = list(b0=st1.1[i,1],b1=st1.1[i,2],b2=st1.1[i,3])  ) 
 }
```

This isn't technically an issue with the package but I have nowhere else to ask such questions in relation to doAzureParallel. Many thanks in advance.

**Comment by paselem** [comment] 2017-11-27 18:28
@simon-tarr - this is a good point and a pain-point of merging large runs for a parallel workflow.

Essentially, I think the bottleneck is during the merging phase downloading all of the individual results to a single node for the final aggregation. This is what the process looks like:

Per node, we run a collection of tasks. If your chunk size is greater than 1, we will run multiple iterations on a single R session, which is usually a good way to improve runtimes. Each 'chunk' will produce it's own output which will be uploaded to storage for the merge task to pick up later. 
```sh
STORAGE    | MERGE TASK ON NODE                      | STORAGE
-----------|-----------------------------------------|------------------------
result_1 --|                                         |
result_2 --|                                         |
result_3 --|-- download individual files and merge --|--> upload merged result
...      --|                                         |
result_n --|                                         |
```
Having to iterate over 500K files (especially if they are small) is a huge tax to pay on a single node. One recommendation that comes to mind is to do a local reduce on each node (assuming your chunk size is > 1) to reduce the number of files and the download penalty per file. Essentially you will combine several results locally on a single node, reducing the total number of files you upload to storage and the amount of data the merge task needs to process.

The new flow would look like this (assuming a chunk size of 8).
```sh
NODE                           | STORAGE  | MERGE TASK ON NODE | STORAGE 
--------|----------------------|----------|-----------------------------------
task_1--|                      |          |                    |
task_2--|   Reduce. Upload     |          |                    |
task_3--|-> single result   -> | result_a |                    |
...   --|   for entire chunk   |          |    download        |
task_8--|                      |          |    individual      |     upload
                                          | -- files           | --> merged
task_9--|                      |          |    and             |     result
task_10-|   Redulce. Upload    |          |    merge           |
task_11-|-> single result   -> | result_b |                    |
...    -|   for entire chunk   |          |                    |
task_16-|                      |          |                    |
```
This would help reduce the total payload for the merge task to run by ~8x and pre-loads some of the merge work onto every reduce component of each node, distributing that workload across the cluster.

More information on using the reduce is in the man pages for the package:
```R
??setReduce
```

**Comment by simon-tarr** [comment] 2017-11-28 08:49
Hello @paselem thank you for the reply and detailed look as to what's going on.

I've noticed that when all the processing has completed (i.e. the job progress is at 100%) all nodes in the pool are sat at idle, indicating that the processing has completed in the cloud. My local machine's CPU then increases to 10-15% utilisation and will apparently be processing something for hours. After this has completed, my local R session stops processing and the object is fully returned.

Given the node state being idle and the uptick in local CPU usage after the computation, I assumed that my computer was carrying out the merging of individual files, not a single node in the pool. Given what you've said above, however, that doesn't seem to be the case?

I've been setting an appropriate chunk size as per the documentation (number of iterations / number of cores). I will try using setReduce this morning to see whether I can improve the overall processing time.

**Comment by paselem** [comment] 2017-11-28 16:14
Hi @simon-tarr,
I think I see what you're saying now, which is different to what I originally understood the problem to be. I think there is not too much you can do to optimize the running of doAzureParallel (which is what I previously mentioned). I *think* this issue is that the piece of data you have to pull down from the cloud is large and takes time to download and load into memory. Do you know the size of the final output from the parallel loop?

If you're not sure, you can find this by looking in the Azure Portal.

Azure Portal -> Azure Storage Account -> Browse Blobs. Type in the name of the job in the 'search by container prefix'. Then simply look for a file called JOB_ID-merge.rds. For example "job20170218071925-merge.rds". It will have the file size next to it. This file will contain the fully merged results of your entire job.

Thanks,
-Pablo

Thanks,
-Pablo

**Comment by simon-tarr** [comment] 2017-11-28 16:58
Yeah I think the cloud-side of things in terms of processing is perfect, it's just returning the result which is causing the bother.

Although the original list is large (500k), I've asked the loop to not return any iterations which error. Although really, this doesn't work. If I run the loop locally using a subset of the data (n=10,000 for speed) using %do% I'll get a list returned of length zero (i.e. none of the models converged, therefore each iteration threw an error, therefore nothing was returned). However, running %dopar% and sending to Azure I get returned the convergence error message for each iteration, even when .errorhandling is set to 'remove'. I guess it's possible that the local slowdown I'm seeing is R trying to handle a list of length 500,000!

In response to checking the file sizes: merge.rds is only 37 bytes. The whole job container is less than 100Mb in size.

Thanks
Simon

**Comment by paselem** [comment] 2017-11-29 20:27
@simon-tarr 
We took a look at the code, and it seems like we may not be handling the case where .errorhandling is set to remove and returning results incorrectly. We're looking into it now and will get back to you on it.

**Comment by simon-tarr** [comment] 2017-11-30 11:07
Okay great, hopefully it's an easy fix.

**Comment by paselem** [comment] 2017-11-30 23:23
Hello @simon-tarr, is this what you're seeing?

![image](https://user-images.githubusercontent.com/11393045/33460186-dbd2e2b4-d5e1-11e7-953c-c57ba4caac81.png)

What we _think_ might be happening is that downloading all of the error file references (in the Viewer on the right) on your machine is taking a very long time since there are so many of them. We will publish a fix to only download the first 10 error references in the viewer and see if that fixes the issue where you're seeing.

**Comment by simon-tarr** [comment] 2017-12-01 09:13
Hi @paselem with regards to your original reply about downloaded tasks; that's exactly what I'm seeing, yes.
With regards to your second edit, I'm happy to give this a try. However, I don't fully understand the documentation. Where exactly do I tell the loop to use .setReduce()? I thought I could use it like this:

```
 cs <- ceiling(nrow(no.iter) / getDoParWorkers())
 opt <- list(chunkSize = cs, setReduce=cs)

my.loop<-foreach(i = 1:nrow(st1), .errorhandling=c('remove'), .options.azure = opt) %do% {
   myloop()
 }
```

**Comment by paselem** [comment] 2017-12-01 19:18
@simon-tarr,

We have identified one other potential issue in our tools performance and one usability bug (reporting 100% done when it's really not done). These are tracked under #178  and #179.

Regarding using the setReduce() I'm not sure if it will actually help address your issue. I know we've been going back and forth on this (sorry!). We are looking at ways at improving the speed of our merge task and potentially find a way to not pull in data files we probably don't need. These will be bundled into our v0.6.2 which we're targeting to release mid-next week.

W.R.T. to the set reduce, the way to use it is not within the foreach, but just before (similar to registering the back end)

```R
# Run with a local reducer:
doAzureParallel::setReduce(cs)
my.loop<-foreach(i = 1:nrow(st1), .errorhandling=c('remove'), .options.azure = opt) %dopar% {
   myloop()
 }

# Remove the reducer
doAzureParallel::setReduce(NULL)
my.loop<-foreach(i = 1:nrow(st1), .errorhandling=c('remove'), .options.azure = opt) %dopar% {
   myloop()
 }
```

**Comment by simon-tarr** [comment] 2017-12-04 11:43
Hi @paselem thanks for the update. I think I'm going to stop tinkering with getting the current release to work within my workflow and wait until 0.6.2. Many thanks for the communications.

**Comment by paselem** [comment] 2017-12-07 16:54
Hi @simon-tarr, we unfortunately are taking a bit longer to release these changes than we'd like. We had to postpone some of the performance improvements until the next release, but will have better monitoring as part of this release (shipping later today as v0.6.2). If possible, please have a look and try it out to see if it helps identify any bottlenecks. Essentially we are trying split up the processing of the parallel tasks vs. the processing of the merge. This should give us a definitive answer around where the bottleneck is in your case.

**Comment by simon-tarr** [comment] 2017-12-12 08:44
Hi @paselem I've been trying the new version (v0.6.2 and rBatch 0.5.3) and have seen some improvements in speed when running lists <100,000 long. I'm still encountering some long wait times for anything >~200,000. 

Regardless of list length, however, I'm finding that it's taking a very long time for the job to properly start with large lists (which are not large in a file size sense). For example, I can wait hours sometimes are hitting run for the progress bar to appear. I'll be stuck looking at this:

```
Job Summary: 
Id: job20171212000000
```

I thought that maybe it's taking some time to upload the list that needs to be processed but the list is only 2.3MB. If I check portal.azure.com all nodes are shown as 'running'. I guess something is happening up in the cloud but I can't see or figure out what that something is.

The good news however is that .errorhandling='remove' is now working as expected (when a job is finally returned).

**Comment by paselem** [comment] 2017-12-12 17:35
@simon-tarr, the long time to wait for all tasks to fully render in Batch is expected but there is probably room for improvement. What is happening on your machine is that we're splitting up the work and creating the execution graph in service. Since you have so many tasks it is taking us a long time to build the graph. We will take a look and see if we can improve this performance. Regardless though, your work will start to execute as soon as the first chunk of work is scheduled, so by the time you're done scheduling, you should already see a reasonable amount of progress. 

The job sitting at 'Merging tasks...' for a long time confirms that this is indeed the bottleneck in your workflow. I am wondering if we can optimize the run-time by ignoring failed tasks in the merge since you're using the errorhandling='remove' option but I believe it is a non-trivial change. We have already started work on improving the performance though and will spend a few more days finishing it off before we release it to make sure we didn't introduce any regressions.

I'm happy that the errorhandling options are working as expected, but cannot give you any more pointers other than 'wait for our performance fixes' in the next few days to help with you long wait times. We'll loop back around once it's ready.

Thanks for all the feedback!
Pablo

**Comment by brnleehng** [comment] 2017-12-19 17:42
Hi @simon-tarr 

#194 I've added a PR to speed up merging the tasks by enabling doParallel. If you currently want to test your workload, here's a snippet of code.

``` R
devtools::install_github("Azure/doAzureParallel", ref = "fix/merge-task-perf")
```

Thanks!
Brian

**Comment by simon-tarr** [comment] 2017-12-20 07:47
Hi @brnleehng thanks very much! I shall give this a try today and will report back!

**Comment by simon-tarr** [comment] 2017-12-20 09:05
I've noticed that I have started to get this error after each job has run (regardless of list size):

> An error has occurred in the merge task of the job 'job20171220085700'. Error handling is set to 'stop' and has proceeded to terminate the job. The user will have to handle deleting the job. If this is not the correct behavior, change the errorHandling property to 'pass'  or 'remove' in the foreach object. Use the 'getJobFile' function to obtain the logs. For more information about getting job logs, follow this link: https://github.com/Azure/doAzureParallel/blob/master/docs/40-troubleshooting.md#viewing-files-directly-from-compute-node

What's curious is that I get this message no matter what I set .errorhandling() to. When the above  message was generated, .errorhandling was set to 'remove'.

I can confirm that I also receive this error when using the previous master branch of the package (and not just your #194 fix posted above).

Is this behaviour expected?

**Comment by brnleehng** [comment] 2017-12-20 18:55
Hi @simon-tarr 

Can you share your stderr.txt and R log txt? Also do you have a sample that I can test with? That'll help me in testing this out.  

I've updated the task status progress bar to be more verbose. There appears to be an error on the merge task specifically. Since there's an error on the merge task, we have terminated the job since we cannot guarantee if the merged result has been uploaded to storage or not. It is expected behavior. 

Thanks!
Brian

**Comment by simon-tarr** [comment] 2017-12-21 09:47
Hi @brnleehng 

Thanks for the reply. I am still a little confused about the error message though. It's saying that error handling is set to 'stop' which is definitely not the case (it's set to 'remove').

Below is some sample code that will hopefully let you troubleshoot the issue. I don't know whether the errors are due to my specific data so I have included a download link to the exact data that I'm using. 

I'm trying to find start values to fit an exponential model. It is completely possible that there are no start values which will enable model fitting. In this case, I expect all iterations to fail (an error about convergence). However I'm hoping that a handful of the loop's iterations start values will enable a model to be fit (thus not producing an error). It is these iterations that I hope to return (hence setting .errorhandling="remove").

I apologise for a lack of a general reproducible example.

Data: https://1drv.ms/u/s!AlF85N0khZNl9s9ZhhBMI-PB5YGyHQ 

```
xx.df<-read.csv("your/file/path/to/downloaded/csv")

xx.df<-as.data.frame(cbind(xx.df$xx,xx.df$xx2))

xx.df<-na.omit(xx.df)

 st1 <- expand.grid(b0 = seq(-145, 145, length=100), b1 = seq(-145, 145, length=100), b2 = seq(-145, 145, length=100))

 cs <- ceiling(nrow(st1) / getDoParWorkers())
 opt <- list(chunkSize = cs)

 mod1.1<-foreach(i = 1:nrow(st1), .errorhandling="remove", .options.azure = opt, .packages=c("nls")) %dopar% {
   mod1.1[[i]]<-nls(xx2~b0+b1*exp(b2*xx), data=xx.df, start = list(b0=st1[i,1],b1=st1[i,2],b2=st1[i,3])) 
 }
```

I have been running a pool of 16 x Standard_F16 machines using rocker/tidyverse:latest

**Comment by brnleehng** [comment] 2017-12-21 19:15
@simon-tarr 

Ahh misread the error message, the error message is incorrect. The error handling is 'stop' is a default message.  
 
I've started running your sample. I've ran into some issues with "nls" package. The "nls" package is not available in CRAN. It appears that the 'stats' package contains the nls function now and they've deprecated 'nls' package. 

Currently, running the sample. I'll update this thread with my results

Thanks for all the feedback!

**Comment by paselem** [comment] 2018-01-25 23:24
@simon-tarr - I wanted to ping on this thread to let you know we're still working on the performance of the merge task. It has been much more involved that we originally expected but we're hopeful that once we have it ready it will improve the run time for your scenario significantly. We're still have some work to do but wanted to send a message letting you know it is one of the big updates for our next release.

Thanks!

**Comment by simon-tarr** [comment] 2018-01-29 09:57
Hi @paselem thanks very much for the update - I'm looking forward to it dropping! I've been getting on okay with the current version but the merge times are quite a pain sometimes as they don't seem to scale linearly with the input job size. Fingers crossed the new update will fix it. 
All the best
Simon

**Comment by brnleehng** [comment] 2018-03-16 17:56
Hi @simon-tarr 

We made a couple of changes to improve the performance of the run time in your scenario. First, we move the errorHandling 'remove' case into the worker script instead of the merge task. The merge task had to process all of the errors before creating a list of results.  Second, we added an optional task retry count. By default, we had it set to 3. However, in your scenario, it seems that errors are more common. Therefore you should be able to set it to 1 instead of running the entire task again.

Installation:
``` R
devtools::install_github("Azure/doAzureParallel", ref = "fix/merge-task-perf")
```

Test Script:
``` R 
# import the doAzureParallel library and its dependencies
library(doAzureParallel)

# set your credentials
setCredentials("credentials.json")

# Create your cluster if not exist
cluster <- makeCluster("cluster.json")

# register your parallel backend
registerDoAzureParallel(cluster)

# check that your workers are up
getDoParWorkers()

xx.df<-read.csv("dataframe.csv")

xx.df<-as.data.frame(cbind(xx.df$xx,xx.df$xx2))

xx.df<-na.omit(xx.df)

st1 <- expand.grid(b0 = seq(-145, 145, length=100), b1 = seq(-145, 145, length=100), b2 = seq(-145, 145, length=100))

cs <- ceiling(nrow(st1) / getDoParWorkers())
opt <- list(chunkSize = cs, taskRetryCount = 2, autoDeleteJob = FALSE)

start_p <- Sys.time()
mod1.1<-foreach(i = 1:nrow(st1), .errorhandling="remove", .options.azure = opt) %dopar% {
    nls(xx2~b0+b1*exp(b2*xx), data=xx.df, start = list(b0=st1[i,1],b1=st1[i,2],b2=st1[i,3]))
}
end_p <- Sys.time()

difftime(end_p, start_p, unit = "min")
``` 

Let me know if this has improved your scenario, then we will merge the PR. Both of these changes are still in PR. #235  and #223 

Thanks for your patience!
Brian

**Closed** 2018-09-13 16:30 UTC
