### ISSUE TITLE
Workers don't contain functions defined in .GlobalEnv and .Rprofile from container image ignored

### ISSUE THREAD

**Issue by roumail** [Azure/doAzureParallel#205] opened 2018-01-24 14:14 UTC
I receive the following error when trying to run a parallel job. The job was changed to be trivial but still I receive the same issue:
```
result <- foreach(i = 1:10, .errorhandling = 'stop') %dopar% {
    1
}
```

**Error**: 
Authentication failed

**Message**:
Server failed to authenticate the request. Make sure the value of the Authorization header is formed correctly including the signature. 

**Authentication detail:**
Signature did not match. String to sign used was w 2018-01-22T13:01:42Z 2018-01-25T13:01:42Z /blob/rohinfrasandssabatch901/$root 2016-05-31

You may think that the error is with the credentials I provide, but I am able to run the monte carlo simulation problem (https://azure.microsoft.com/en-us/blog/doazureparallel/) without any problem, so the error is probably not coming from my credentials.

Maybe I need to set some environment variables at the cluster startup or something? The code fails as soon as I get to the parallel algorithm part. 

Please let me know if there is additional information you need. Any pointers would be very much appreciated.

**Comment by paselem** [comment] 2018-01-24 18:27
@roumail thanks for bringing this up. Unfortunately I was not able to reproduce the issue. Here is my code
```R

# Prepare cluster
workerClusterConfig <- list(
  "name" = "worker",
  "vmSize" = "Standard_F2",
  "maxTasksPerNode" = 2,
  "poolSize" = list(
    "dedicatedNodes" = list("min" = 0, "max" = 0),
    "lowPriorityNodes" = list("min" = 1, "max" = 3),
    "autoscaleFormula" = "QUEUE"
  ),
  "containerImage" = "rocker/tidyverse:latest",
  "rPackages" = list(
    "cran" = list(),
    "github" = list(),
    "bioconductor" = list()
  ),
  "commandLine" = list()
)

workerCluster <- doAzureParallel::makeCluster(workerClusterConfig, wait = FALSE)
doAzureParallel::registerDoAzureParallel(workerCluster)

# Run job
result <- foreach(i = 1:10, .errorhandling = 'stop') %dopar% {
  1
}


```

And here is my output:
```sh
> result <- foreach(i = 1:10, .errorhandling = 'stop') %dopar% {
+   1
+ }
==================================================================================================================================================================
Id: job20180124182248
chunkSize: 1
enableCloudCombine: TRUE
errorHandling: stop
wait: TRUE
autoDeleteJob: TRUE
==================================================================================================================================================================
Submitting tasks (10/10)
Submitting merge task. . .
Waiting for tasks to complete. . .
| Progress: 100.00% (10/10) | Running: 0 | Queued: 0 | Completed: 10 | Failed: 0 |
Tasks have completed. Merging results..
```


Do you happen to have any other settings on your cluster? Also, can you provide more details on the error for example when it happened? Did the foreach fail out right away?

Thanks!

**Comment by brnleehng** [comment] 2018-01-24 20:15
Hi @roumail 

Can you also share your sessionInfo()? 

Thanks,
Brian

**Comment by roumail** [comment] 2018-01-25 09:50
Hello @brnleehng, @paselem. Thank you for your responses. I have changed the title of my issue as I've tried a few things already and understand the problem better:

- While my jobs were failing, I was extracting the wrong error message for the failing tasks, i.e. **please ignore the error message above :)**
- I am not calling my trivial parallel from the same script. My workflow is the following:
1. Launcher script containing knitr::render
2. The markdown report sources the functions I've defined, calling a wrapper function I use
3. Within this calling stack, everything goes well until I approach my call to foreach %dopar%. Running the trivial call to foreach, given below, I don't encounter any problems and my job runs as expected: 
```
# Run job
result <- foreach(i = 1:10, .errorhandling = 'stop') %dopar% {
  1
}
```
However, when I try my actual workflow, where my call to foreach %dopar% looks more like this:
```
# Actual job
result <- foreach(i = 1:10, .errorhandling = 'stop') %dopar% {
# call function that is defined in .GlobalEnv
  out <- some_func_in_global_env()
  out
}
```
Each of my task(workers) fail with the error that `some_func_in_global_env` was not found. I found this quite odd since I expect that due to forking, I don't need to export variables from my global environment to the workers. However, looking at the workspace on one of my failing workers, I can clearly see that all the functions defined in my global environment are not available on the workers. The only things defined are a few Azure related variables (see screen shot):

![image](https://user-images.githubusercontent.com/32498483/35381443-9616b10e-01bc-11e8-9383-a0ad1846499c.png)

I saved the session info and workspace image before the call to foreach as well in case that might help. Looking forward to your response and thanks in advance for any tips and suggestions!

Rohail

**Comment by roumail** [comment] 2018-01-25 16:03
Please find attached a minimal example that recreates the error. The following files are available in this zip:

- LAUNCHER.R 
o	Here the person running this file needs to specify the project directory
o	The poolname would also need to be changed
o	The cluster uses the container image, roumail/g2n-env, which I would want to use for successfully running this example.
- credentials.json
o	Here we need to specify the batch/storage account details etc
- functions.R
o	This file contains some dummy functions that are sourced by the main_report.Rmd file.
o	The following parameters to foreach have been commented out: ‘.export’ and ‘.package‘. They partially solve the problem, but not entirely. 
- main_report.Rmd: A markdown document that loads packages, sources the functions and calls them. If everything goes well, you would have a markdown report generated in your directory.

The errors I receive are that the ‘changepoint’ package is not found during the parallel execution or that the load_data() function from my global environment is not found. 

Normally, I wouldn't expect this problem since we are 'forking', so I shouldn't need to pass my global environment via .export to foreach. These problems are really on the 'jobpreparation' step. 

[azure_test.zip](https://github.com/Azure/doAzureParallel/files/1664644/azure_test.zip)

**Comment by paselem** [comment] 2018-01-25 16:50
@roumail thanks for the detailed explanation and repro steps. From the surface I'm not exactly sure what the issue is but I have a hunch that we are not passing the environment in a way that the render command expects us to.

As a side question (not related to this issue), can you give me a bit of context around what you're calling registerDoSEQ() at the end of your script?

**Comment by paselem** [comment] 2018-01-25 18:52
@roumail we have identified the issues and have local fixes for them.

There are basically two issues that were
1. doParallel doesn't do the best job at resolving function dependencies. You need to manually pass them into the foreach function using the .export command so that they are available in the cluster.

```R
result <- foreach::foreach(i = 1:10,
                             .export = c('load_data')) %dopar% {
# algorithm
}
```

2. doAzureParallel had an issue where the resolution of packages at package install time and script run time was inconsistent. In your specific case, the 'changepoint' package was already available in your image in a path that was read by the package installer code (defined in ~/.RProfile) but was not read by the run time code. We have a fix #209 out for review to address the issue.

For a complete sample of what I did, please take a look at the following
```R
## Set up cluster
devtools::install_github('azure/doAzureParallel', ref = 'master')
library(doAzureParallel)

# set your credentials
credentials <- list(
  ...
)
doAzureParallel::setCredentials(credentials)

# set cluster config
workerClusterConfig <- list(
  "name" = "rou",
  "vmSize" = "Standard_F4",
  "maxTasksPerNode" = 4,
  "poolSize" = list(
    "dedicatedNodes" = list("min" = 0, "max" = 0),
    "lowPriorityNodes" = list("min" = 1, "max" = 1),
    "autoscaleFormula" = "QUEUE"
  ),
  "containerImage" = "roumail/g2n-env", #"rocker/tidyverse:latest",
  "rPackages" = list(
    "cran" = list(),
    "github" = list(),
    "bioconductor" = list()
  ),
  "commandLine" = list()
)

workerCluster <- doAzureParallel::makeCluster(workerClusterConfig, wait = FALSE)
doAzureParallel::registerDoAzureParallel(workerCluster)


## Define Functions
load_data <- function() {
  out <- iris
  out

}

level_0 <- function() {
  result <- foreach::foreach(i = 1:10,
                             .errorhandling = 'stop',
                             .export = c('load_data')
  ) %dopar% {

    out <- load_data()


    set.seed(1)
    x <- c(rnorm(100, 0, 1), rnorm(100, 0, 10))
    ansvar <- changepoint::cpt.var(x)
    #length(ansvar)
  }
  c(result)
}
```

Finally, printing out the result I see the following (trimmed) output:
```sh
[[1]]
Class 'cpt' : Changepoint Object
       ~~   : S4 class containing 12 slots with names
              cpttype date version data.set method test.stat pen.type pen.value minseglen cpts ncpts.max param.est 

Created on  : Wed Dec 13 15:28:54 2017 

summary(.)  :
----------
Created Using changepoint version 2.2.2 
Changepoint type      : Change in variance 
Method of analysis    : AMOC 
Test Statistic  : Normal 
Type of penalty       : MBIC with value, 15.89495 
Minimum Segment Length : 2 
Maximum no. of cpts   : 1 
Changepoint Locations : 100 

[[2]]
...
```

Please keep an eye out for the #209 PR which should make it into master today.

Thanks!

**Comment by roumail** [comment] 2018-01-25 20:23
Hi @paselem ,

Thanks for your responses! For the first problem, I was doing something like .export = ls(globalenv()) to get around the variable export problem. Feels a bit hacky, since if my global environment is big, it adds unnecessary overhead. Ofcourse, in this example, its easy to see load_data is the only variable that needs to be exported, but this could be difficult to figure out. I didn't expect that I needed to use the .export argument since this is normally needed for Psock clusters and not for forks if I'm not wrong? Are there plans in the future to implement something similar to the doFuture backend, which only exports what's needed?

As for the second answer, that really helps. I kept thinking there was something wrong with my image and had verified multiple times that all the packages are installed and loaded. 

Thank you very much for the help. Looking forward to the latest update

**Comment by roumail** [comment] 2018-01-25 20:45
Btw, `devtools::install_github('azure/doAzureParallel', ref = 'master')` throws an error: 

```
Downloading GitHub repo azure/doAzureParallel@master
from URL https://api.github.com/repos/azure/doAzureParallel/zipball/master
Installing doAzureParallel
Error in data.frame(package = package, installed = installed, available = available,  : 
  row names contain missing values
```

Not sure if you faced the same. I will wait! Thanks again!

**Comment by paselem** [comment] 2018-01-25 20:55
@roumail are you on Windows or Linux?
We have seen intermittent issues on Windows machines where you need to install 'azure/rAzureBatch' prior to installing 'azure/doAzureParallel'. Can you give that a try?

**Comment by roumail** [comment] 2018-01-25 20:58
Hi, I'm on Linux. I tried installing rAzureBatch first (succeeds) but still get the same error for doAzureParallel

**Comment by paselem** [comment] 2018-01-25 21:35
@roumail 
Two things:
1. We have a PR out with the changes I described above. Before we merge them in, can you try to validate it locally and make sure it works?
```R
devtools::install_github('azure/doazureparallel', ref='feature/loadLocalRSessionInfo')
```

2. Regarding the failing install, is this happening on the same machine you were using before? If not, is this a new box? Can you give me your sessioninfo?
```R
sessionInfo()
```

**Comment by paselem** [comment] 2018-01-25 21:57
Actually, I just remembered we had the install issue from another customer and it was resolved by upgrading the version of devtools. https://github.com/Azure/doAzureParallel/issues/203

**Comment by roumail** [comment] 2018-01-26 09:26
Hi @paselem,

#203 fixes the installation issue. Running the script you posted earlier, with the updated version of doAzureParallel, I seem to be getting a new error. 

This time it is a job preparation error, where docker run fails with an exit code 125. Probably the flags passed to it? I am able to run the docker myself and can verify that all the packages are installed, etc. 

![image](https://user-images.githubusercontent.com/32498483/35432605-e0e6f288-0280-11e8-82cf-6e5947fb583e.png)

Sessioninfo:
```
R version 3.3.2 (2016-10-31)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.8 (Santiago)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rmarkdown_1.6         knitr_1.15            doAzureParallel_0.6.2 iterators_1.0.9       foreach_1.4.4        

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12      bindr_0.1         magrittr_1.5      lattice_0.20-34   rjson_0.2.15      R6_2.2.2         
 [7] rlang_0.1.1       dplyr_0.7.2       stringr_1.2.0     httr_1.3.1        tools_3.3.2       grid_3.3.2       
[13] rAzureBatch_0.5.4 htmltools_0.3.5   assertthat_0.2.0  yaml_2.1.13       digest_0.6.12     rprojroot_1.2    
[19] tibble_1.3.3      bindrcpp_0.2      bitops_1.0-6      codetools_0.2-15  changepoint_2.2.2 RCurl_1.95-4.10  
[25] curl_3.0          glue_1.2.0        evaluate_0.10     mime_0.5          stringi_1.1.5     backports_1.1.1  
[31] jsonlite_1.5      zoo_1.8-0         pkgconfig_2.0.1  

```

**Comment by paselem** [comment] 2018-01-26 16:13
@roumail I think this is expected. Since we don't know what you have installed on your machine, you need to manually let us know by either doing
```R
package::my_package.var()
```
or
```R
library(my_package)
var()
```

**Closed** 2018-02-20 16:18 UTC
